export const posts = [
  {
    id: 1,
    userId: 101,
    userName: "Rikka",
    avatar: "./resources/test photos/test-user-img.jpg",
    time: "3 hours ago",
    content: "Small progress every day creates big change over time.",
    image: "./resources/test photos/test-user-img.jpg",
    likes: 128,
    comments: 32,
    isLiked: false,
    isCollected: false,
    topic: "study",
  },
  {
    id: 2,
    userId: 102,
    userName: "Taffy",
    avatar: "./resources/test photos/test-user-img.jpg",
    time: "5 hours ago",
    content: "Discipline matters more than motivation in difficult moments.",
    image: "",
    likes: 95,
    comments: 18,
    isLiked: true,
    isCollected: false,
    topic: "life",
  },
  {
    id: 3,
    userId: 103,
    userName: "Miku",
    avatar: "./resources/test photos/test-user-img.jpg",
    time: "1 day ago",
    content:
      "Body text for a post. Since it's a social app, sometimes it's a hot take, and sometimes it's a question.",
    image: "./resources/test photos/test-user-img.jpg",
    likes: 201,
    comments: 44,
    isLiked: false,
    isCollected: true,
    topic: "music",
  },
];
